"""baseline

Revision ID: 5e83d7ff8d89
Revises:
Create Date: 2026-08-10 10:43:27.131362

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5e83d7ff8d89"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
