"""add user ownership to notes

Revision ID: b13685945f65
Revises: 5e83d7ff8d89
Create Date: 2026-08-10 11:06:24.647753

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b13685945f65"
down_revision: str | Sequence[str] | None = "5e83d7ff8d89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column temporarily nullable because existing notes need ownership
    op.add_column(
        "notes",
        sa.Column("user_id", sa.Integer(), nullable=True),
    )

    # Assign existing notes to existing test user
    op.execute(
        """
        UPDATE notes
        SET user_id = 1
        WHERE user_id IS NULL
        """
    )

    # Make user_id required after data migration
    op.alter_column(
        "notes",
        "user_id",
        nullable=False,
    )

    # Add foreign key constraint
    op.create_foreign_key(
        None,
        "notes",
        "users",
        ["user_id"],
        ["id"],
    )

    # Add index
    op.create_index(
        op.f("ix_notes_user_id"),
        "notes",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_column("notes", "user_id")
    # ### end Alembic commands ###
